LSB header modified, return codes modified

diff --git a/log2ram b/log2ram
--- a/log2ram
+++ b/log2ram
@@ -1,28 +1,26 @@
 #!/bin/sh 
 
 ### BEGIN INIT INFO
-# Provides:          
+# Provides:          log2ram
 # Required-Start:    $syslog
 # Required-Stop:     $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Example initscript
-# Description:       This file should be used to construct scripts to be
-#                    placed in /etc/init.d.  This example start a
-#                    single forking daemon capable of writing a pid
-#                    file.  To get other behavoirs, implemend
-#                    do_start(), do_stop() or other functions to
-#                    override the defaults in /lib/init/init-d-script.
+# Short-Description: log2ram prevents constant I/O writes on systems running on SSD or SDcard.
+# Description:       This program mount /var/log as a tmpfs keeping logs in RAM.
+#                    On the specified cron job, logs are writen to /var/log.hdd periodically.
+#
+# Modification:	   Script modified to be used by all LSB based systems.
+#							Pre-check is made if log2ram is already mounted, which prevents over usage of RAM
 ### END INIT INFO
 
 # Author: azlux <azlux@outlook.com>
-# Modified by: fugitive90 
-#
-PATH="/sbin:/bin/:/usr/bin/:/usr/local/bin"
-DESC="Log2Ram is preventing constant disk I/O on embeded system, saving its lifetime. Modified for SysV system"
+# Modified by: fugitive90 <fugitiv3@protonmail.com>
+# Compactible by all LSB based systems
 
-#HDD_LOG=/var/log.hdd/
-#RAM_LOG=/var/log/
+
+PATH="/sbin:/bin/:/usr/bin/:/usr/local/bin"
+
 LOG2RAM_LOG="/var/log.hdd/log2ram"
 
 [ $( id -u ) -ne 0 ] && echo "Must be run as root. Exiting." && exit 2
@@ -31,7 +29,7 @@ LOG2RAM_LOG="/var/log.hdd/log2ram"
 . /lib/lsb/init-functions
 
 # Load config 
-[ -f "/etc/default/log2ram.conf" ] && CONFIG="/etc/default/log2ram.conf" && . $CONFIG || log_failure_msg "Config file not found"
+[ -f "/etc/log2ram.conf" ] && CONFIG="/etc/log2ram.conf" && . $CONFIG || log_failure_msg "Config file not found!"
 [ -z $CONFIG ] && exit 2
 
 
@@ -71,7 +69,11 @@ sync_from_disk () {
     else
         cp -rfup "/var/log.hdd" -T "/var/log" > "${LOG2RAM_LOG}.log" 2> "${LOG2RAM_LOG}.err" 
     fi
+
+	 return 0 
 }
+
+
 check_is_mounted ()
 {
 	local ec
@@ -95,9 +97,9 @@ umount_log ()
 	if [ $? -eq 0 ];then
 		umount -l "/var/log" && _rc_log=0
 		umount -l "/var/log.hdd" && _rc_log_hdd=0
-		[ -n $_rc_log ] && [ -n $_rc_log_hdd  ] && log_success_msg "log2ram umounted"
+		[ -n $_rc_log ] && [ -n $_rc_log_hdd  ] && log_success_msg "log2ram umounted."
 	else
-		log_warning_msg "log2ram is not mounted"
+		log_warning_msg "Log2ram is not mounted"
 	fi
 
 }
@@ -107,7 +109,7 @@ do_start ()
 {
 	
    [ -d "/var/log.hdd" ] || mkdir "/var/log.hdd"
-   test -f "${LOG2RAM_LOG}.log"  && rm "${LOG2RAM_LOG}.log"  
+   test -f "${LOG2RAM_LOG}.*"  && rm "${LOG2RAM_LOG}.*"  
    
 	check_is_mounted
 	if [ $? -ne 0  ]; then
@@ -115,9 +117,9 @@ do_start ()
    	mount --make-private "/var/log.hdd"
    	mount -t tmpfs -o nosuid,noexec,nodev,mode=0755,size=$SIZE log2ram "/var/log"
    	sync_from_disk && log_success_msg "Log2Ram is running"
-		touch /var/log.hdd/log2ram.lock # this will overwrite anyway
+		touch /var/log.hdd/log2ram.lock
 	else
-		log_warning_msg "Log2Ram already mounted"
+		log_warning_msg "Log2ram is already mounted."
 		exit 2
 	fi	
 
@@ -125,7 +127,7 @@ do_start ()
 do_stop ()
 {
 	check_is_mounted 
-	test $? -eq 0 && sync_to_disk
+	[  $? -eq 0 ] && sync_to_disk
 	umount_log
 }
 do_reload ()
@@ -135,7 +137,7 @@ do_reload ()
    	sync_to_disk
 	   exit 0
 	else
-	  log_warning_msg "Log2Ram not mounted. Files not synced!"
+	  log_warning_msg "Log2ram not mounted. Files not synced!"
 	  exit 2 
 	fi
 
@@ -152,7 +154,7 @@ case "$1" in
 		do_reload
 		;;
 	*)
-      echo "Usage: log2ram {start|stop|init|write}" >&2
+      echo "Usage: log2ram {start|stop|reload}" >&2
       exit 1
       ;;
 esac
